<?php
echo "<!DOCTYPE html>";
echo "<html><head>";
echo "<meta name='viewport' content='width=device-width, initial-scale=1'>";
echo "<meta charset='utf8'>";
echo "<title>";
echo $pageTitle;
echo "</title>";
echo "<style>";
echo "* { box-sizing: border-box;}";
echo "body{color:".$colors['txtColor'].";background-color:".$colors['$bgColor'].";direction:$gdir;}";
echo "#filterBox {background-image: url('images/searchicon.png');background-position: 10px 10px;background-repeat: no-repeat;width: 100%;font-size: 16px;padding: 12px 20px 12px 40px;border: 1px solid #ddd;margin-bottom: 12px;}";
echo "#mainTable {border-collapse: collapse;width: 100%;border: 1px solid #ddd;font-size: 18px;color: ".$colors['listFG'].";background-color: ".$colors['listBG'].";}";
echo "#mainTable th, #mainTable td {text-align: $galn;padding: 12px;}";
echo "#mainTable tr {border-bottom: 1px solid #ddd;}";
echo "#mainTable tr.header, #mainTable tr:hover {background-color: ".$colors['lstHdBG'].";color: ".$colors['lstHdFG'].";}";
echo ".newBtn {background-color: ".$colors['newButtonBg']." ;  color: ".$colors['newButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;margin: auto;}";
echo ".newBtn:hover {opacity: 1;}";
echo ".edtBtn {background-color: ".$colors['editButtonBg'].";  color: ".$colors['editButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".edtBtn:hover {opacity: 1;}";
echo ".delBtn {background-color: ".$colors['deleteButtonBg'].";  color: ".$colors['deleteButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".delBtn:hover {opacity: 1;}";
echo ".savBtn {background-color: ".$colors['saveButtonBg'].";  color: ".$colors['saveButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".savBtn:hover {opacity: 1;}";
echo ".cnlBtn {background-color: ".$colors['cancelButtonBg'].";  color: ".$colors['cancelButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".cnlBtn:hover {opacity: 1;}";
echo ".okBtn {background-color: ".$colors['okButtonBg'].";  color: ".$colors['okButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".oklBtn:hover {opacity: 1;}";
echo ".viwBtn {background-color: ".$colors['viewButtonBg'].";  color: ".$colors['viewButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".viwlBtn:hover {opacity: 1;}";
echo ".yesBtn {background-color: ".$colors['yesButtonBg'].";  color: ".$colors['yesButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".yeslBtn:hover {opacity: 1;}";
echo ".noBtn {background-color: ".$colors['noButtonBg'].";  color: ".$colors['noButtonFg'].";  padding: 10px 10px;  border: none;  cursor: pointer;  width: 100px;  opacity: 0.9;}";
echo ".nolBtn:hover {opacity: 1;}";
echo ".input-container {display: -ms-flexbox; /* IE10 */  display: flex;  width: 100%;  margin-bottom: 15px;}";
echo ".input-field {  width: 100%;  padding: 10px;  outline: none;}";
echo ".input-field:focus {border: 2px solid dodgerblue;}";
echo ".error{color: red; font-size: small;text-align:center;}";
echo ".frmButtons{text-align:center; margin: auto; width: 220px;}";
echo "$customStyles";
echo "</style>";
echo "</head>";
?>